const { dbHelpers } = require('./database');

/**
 * POST /api/quiz/submit
 * 
 * Submit quiz answers and save results
 * 
 * Body: {
 *   userId: number,
 *   quizId: number,
 *   answers: [{questionId, selectedAnswer, isCorrect}, ...],
 *   score: number (out of 10),
 *   timeTaken: number (in seconds),
 *   timeLimit: number (in seconds)
 * }
 */
async function submitQuiz(req, res) {
  try {
    const { userId, quizId, answers, score, timeTaken, timeLimit } = req.body;

    // Validation
    if (!userId || !quizId || answers === undefined || score === undefined) {
      return res.status(400).json({
        success: false,
        message: 'Missing required fields: userId, quizId, answers, score'
      });
    }

    // Ensure score is out of 10
    const scoreOutOf10 = Math.min(Math.max(score, 0), 10);
    
    // Calculate total questions from answers
    const totalQuestions = answers.length || 0;
    
    // Calculate correct answers
    const correctAnswers = answers.filter(a => a.isCorrect).length;
    
    // Calculate weak areas based on incorrect answers
    const weakAreas = answers
      .filter(a => !a.isCorrect && a.topic)
      .map(a => a.topic)
      .filter((topic, idx, arr) => arr.indexOf(topic) === idx); // unique topics

    // Save to database
    const resultId = await dbHelpers.saveResult(
      userId,
      quizId,
      scoreOutOf10,              // score out of 10
      totalQuestions,
      answers,
      weakAreas,
      {
        correctAnswers,
        timeTaken,
        timeLimit,
        accuracy: totalQuestions > 0 ? (correctAnswers / totalQuestions * 100).toFixed(2) : 0
      },
      [] // recommendations (can be generated by AI analyzer later)
    );

    // Return success with result details
    return res.status(200).json({
      success: true,
      resultId,
      message: 'Quiz submitted successfully',
      data: {
        score: scoreOutOf10,
        totalScore: 10,
        correctAnswers,
        totalQuestions,
        accuracy: totalQuestions > 0 ? (correctAnswers / totalQuestions * 100).toFixed(2) : 0,
        timeTaken,
        timeLimit,
        weakAreas
      }
    });
  } catch (error) {
    console.error('submitQuiz error:', error);
    return res.status(500).json({
      success: false,
      message: 'Failed to submit quiz',
      error: error.message
    });
  }
}

/**
 * GET /api/user/history?userId=X
 * 
 * Get all quiz attempts for a user
 */
async function getUserHistory(req, res) {
  try {
    const { userId } = req.query;

    if (!userId) {
      return res.status(400).json({
        success: false,
        message: 'Missing userId parameter'
      });
    }

    const results = await dbHelpers.getUserResults(userId, 50);

    // Parse JSON fields and convert to client format
    const history = results.map(result => ({
      id: result.id,
      quizName: `Quiz ${result.quiz_id}`,
      score: result.score, // already out of 10
      totalScore: 10,
      timeTaken: result.feedback?.timeTaken || 0,
      date: new Date(result.created_at),
      status: result.score >= 7 ? 'passed' : result.score >= 5 ? 'partial' : 'failed',
      correctAnswers: result.feedback?.correctAnswers || 0,
      totalQuestions: result.total_questions,
      accuracy: result.feedback?.accuracy || 0,
      weakAreas: result.weak_areas || [],
      details: result
    }));

    return res.status(200).json({
      success: true,
      data: history
    });
  } catch (error) {
    console.error('getUserHistory error:', error);
    return res.status(500).json({
      success: false,
      message: 'Failed to fetch history',
      error: error.message
    });
  }
}

/**
 * GET /api/user/weakness?userId=X
 * 
 * Get user's weak areas from quiz attempts
 */
async function getUserWeakness(req, res) {
  try {
    const { userId } = req.query;

    if (!userId) {
      return res.status(400).json({
        success: false,
        message: 'Missing userId parameter'
      });
    }

    const results = await dbHelpers.getUserResults(userId, 50);

    // Aggregate weak areas from all attempts
    const weaknessMap = {};
    results.forEach(result => {
      const weakAreas = result.weak_areas || [];
      weakAreas.forEach(area => {
        weaknessMap[area] = (weaknessMap[area] || 0) + 1;
      });
    });

    // Convert to array and sort by frequency
    const weakAreas = Object.entries(weaknessMap)
      .map(([topic, count]) => ({
        topic,
        frequency: count
      }))
      .sort((a, b) => b.frequency - a.frequency);

    return res.status(200).json({
      success: true,
      data: weakAreas
    });
  } catch (error) {
    console.error('getUserWeakness error:', error);
    return res.status(500).json({
      success: false,
      message: 'Failed to fetch weakness data',
      error: error.message
    });
  }
}

module.exports = {
  submitQuiz,
  getUserHistory,
  getUserWeakness
};
